[build]
target = "thumbv7m-none-eabi"

[target.thumbv7m-none-eabi]
rustflags = [
    "-C", "target-cpu=cortex-a9",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
    "-Zlocation-detail=none",
]

[unstable]
build-std = ["core", "compiler_builtins", "panic_abort"]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort", "optimize_for_size"]
