[package]
name = "athook-macros"
authors = ["Sculas"]
version = "0.0.0"
edition = "2024"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1"
hex = "0.4.3"
derive-syn-parse = "0.2.0"