[build]
target = "armv7a-none-eabi"

[target.armv7a-none-eabi]
rustflags = [
    "-Ctarget-cpu=cortex-a9",
    "-Ctarget-feature=+thumb-mode",
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=--nmagic",
    "-Zlocation-detail=none",
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins", "panic_abort"]
build-std-features = ["compiler-builtins-mem", "optimize_for_size"]
